QtecTask/QtecTask/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('keywords.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QtecTask/keywords/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'keywords'

urlpatterns = [
    path('', views.showKeyWords, name='show'),
]

QtecTask/keywords/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class KewWordsMD(models.Model):

    key_word = models.CharField(max_length=100)
    last_search_by = models.CharField(max_length=100)
    last_search_date = models.DateField()
    count = models.IntegerField(default=0)
    result_showed = models.CharField(max_length=200)

    def __str__(self):  # function to_string
        return self.key_word


class SearchDate(models.Model):

    key_word = models.ForeignKey(
        KewWordsMD, related_name='KewWords_tb', on_delete=models.CASCADE)
    user_name = models.CharField(max_length=100)
    search_date = models.DateField()

    def __str__(self):  # function to_string
        return self.user_name

QtecTask/keywords/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .models import SearchDate, KewWordsMD


def showKeyWords(request):

    words = KewWordsMD.objects.all()
    dates = SearchDate.objects.all()

    users = []
    for i in words:
        users.append(i.last_search_by)
    user = set(users)

    dict = {'words': words, 'dates': dates, 'user': user}
    return render(request, 'keyword/show.html', context=dict)

QtecTask/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

      <link rel="stylesheet" type="text/css" href="{% static 'CSS_JS/style.css' %}">
      {% block head %} {% endblock %}
</head>

<body>

      <nav class=" navbar navbar-expand-lg navbar-light  navBackG">
            <div class="container-sm">
                  <a class="navbar-brand" href="{% url 'keywords:show' %}">
                        <span class="qtec">Qtec</span>
                  </a>

            </div>
      </nav>


      {% block body %} {% endblock %}

      {% block body2 %} {% endblock %}

      {% block end %} {% endblock %}




      <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

</body>

</html>

QtecTask/templates/keyword/show.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<title>Show Key words</title>

{% endblock %}


{% block body %}

<div class="container-fluid mt-3">
      <h3>Key Word List:</h3>
</div>
<div class="container mt-4">
      <div class="row">



            <!-- Keywords show-->
            <div class="col-sm-8">
                  <ul class="list-group">
                        {% for i in words%}

                        <li class="mb-3">
                              <ul>{{i.key_word}}</ul>
                              <ul>
                                    <span> Total searched by this key word: </span> <span>{{i.count}}</span><span>
                                          times.</span>
                              </ul>
                              <ul>
                                    <span> Search Result:</span> <span>{{i.result_showed}}</span>
                              </ul>
                              <ul>
                                    <span> Last search by the user: </span><span>{{i.last_search_by}}</span>
                              </ul>
                        </li>

                        {% endfor%}
                  </ul>
            </div>
            <!-- Keywords show end-->



            <!-- filter -->
            <div class="col-sm-4 fiter_border ">
                  <label class="form-check-label" for="task_filter">filter using key word name:</label>
                  <input type="text" id="task_filter" placeholder="Filter Task">


                  <label class="form-check-label mt-3" for="for_first_filters">
                        Show Key-words based on counts:
                  </label>


                  <div id="for_first_filters">

                        <div class="form-check">
                              <input class="form-check-input count" type="checkbox" value=2 id="2_times"
                                    onclick="checkBox()">
                              <label class="form-check-label" for="2_times">
                                    2 times found
                              </label>
                        </div>
                        <div class="form-check">
                              <input class="form-check-input count" type="checkbox" value=5 id="5_times"
                                    onclick="checkBox()">
                              <label class="form-check-label" for="5_times">
                                    5 times found
                              </label>
                        </div>
                        <div class="form-check">
                              <input class="form-check-input count" type="checkbox" value=10 id="10_times"
                                    onclick="checkBox()">
                              <label class="form-check-label" for="10_times">
                                    10 time found
                              </label>
                        </div>
                        <div class="form-check">
                              <input class="form-check-input count" type="checkbox" value=20 id="20_times"
                                    onclick="checkBox()">
                              <label class="form-check-label" for="10_times">
                                    20 time found
                              </label>
                        </div>
                  </div>


                  <label class="form-check-label mt-3" for="for_2nd_filters">
                        Show Key-words based on user name:
                  </label>

                  <div id="for_2nd_filters">
                        {% for i in user%}
                        <div class="form-check">
                              <input class="form-check-input user_name" type="checkbox" value={{i}} id={{i}}
                                    onclick="checkBox()">
                              <label class="form-check-label" for={{i}}>
                                    {{i}}
                              </label>
                        </div>
                        {% endfor %}
                  </div>

            </div>
            <!-- filter end-->



      </div>
</div>
{% endblock %}



{% block body2 %} {% endblock %}

{% block end %}
<script src="{% static 'CSS_JS/script.js' %}" type=""> </script>
{% endblock %}